CREATE DATABASE orders_db;

--INCOMPLETE
CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    added_at TIMESTAMP DEFAUTL CURRENT_TIMESTAMP
)